### ISSUE TITLE
Please show how to child with a turret as a tank game

### ISSUE THREAD

**Issue by pyweeker** [Dot32IsCool/bevy-moving-circle#1]
Hello, several weeks fighting with parent / child in Bevy.
What i am trying to do is : 
- arrow to move the hull
- mouse to rotate the turret, stuck on hull and following his translation
-  left click to fire
Could you go further in your example to show how to implement this ?

here are nice free tank assets : [https://opengameart.org/content/tank-set-2](https://opengameart.org/content/tank-set-2)

**Comment by Dot32Dev** [comment]
ooh, this wasn't an example, this was me trying to learn bevy. I haven't done anything with parents/children :<
sorry for the late reply, i didn't see until just now

**Comment by Dot32Dev** [comment]
Hey, so after you told me about parents/children, i went and added a turret as a child to the player :D 
Instead of rotating the turret however, i am rotating the entire player to look at the mouse.
You can check out the code if you're interested :>
